### ISSUE TITLE
必须用 AppCompat 主题？

### ISSUE THREAD

**Issue by jp1017** [tianzhijiexian/Logcat#1]
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.boyaa.chat/kale.debug.log.ui.LogActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by kaleai** [comment]
对的啊，现在android中都是用这个主题了啊

**Comment by jp1017** [comment]
嗯，一般这样，我找了之前的项目，加入你的库耍了下，就报这个错了，哈哈哈
